apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-template
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            oddbit.com/services: "true"
  template:
    metadata:
      name: "{{name}}-external-secrets"
    spec:
      project: default
      source:
        repoURL: https://github.com/larsks/k8s-external-secrets.git
        targetRevision: HEAD
        path: "overlay/common"
      destination:
        server: "{{server}}"
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 10m
