apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  oddbit.com/services: "true"

resources:
- external-secrets.yaml
- traefik-ingress.yaml
- nginx-ingress.yaml
- cert-manager.yaml
