apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps-template
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-apps"
    spec:
      project: default
      source:
        repoURL: https://github.com/larsks/k8s-argocd-apps.git
        targetRevision: HEAD
        path: "cluster/{{name}}/applications"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 10m
